name: begin_first
description: Item tracker app scaffold
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3

  go_router: ^12.1.3

  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1

  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

  image_picker: ^1.0.5
  flutter_image_compress: ^2.1.0

  geolocator: ^10.1.0
  geocoding: ^2.1.1

  flutter_local_notifications: ^16.2.0
  timezone: ^0.9.2

  permission_handler: ^11.1.0

  uuid: ^4.2.1
  intl: ^0.18.1
  url_launcher: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

  build_runner: ^2.4.7
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.9
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
